config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'topics#index'
  resources :topics do
    collection do
      get :search
    end
  end
  resources :comments, :only => [:create, :destroy]
  resources :categories, :only => [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  validates :name, presence: true, length: { maximum: 30 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  validates :content, presence: true, length: { maximum: 100 }
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  belongs_to :user
  has_many :comments, foreign_key: :topic_id, dependent: :destroy
  has_many :categories, foreign_key: :topic_id, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, length: { maximum: 50 }
  validates :name, length: { maximum: 30 }
  has_many :topics, foreign_key: :user_id
  has_many :comments, foreign_key: :user_id
  has_many :categories, foreign_key: :user_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]

  def create
    @category = current_user.categories.build(category_params)
    @topic = @category.topic
    if @category.save
      flash[:success] = 'カテゴリを追加しました'
      redirect_to topic_path(@topic)
    else
      @comments = @topic.comments.page(params[:page]).per(100).includes([:user])
      @categories = @topic.categories
      @comment = Comment.new
      render template: 'topics/show'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @topic = @category.topic
    if @category.destroy
      flash[:success] = 'カテゴリを削除しました'
    end
    redirect_to topic_path(@topic)
  end

  private

  def category_params
    params.require(:category).permit(:name, :topic_id)
  end

  def correct_user
    @category = Category.find(params[:id])
    redirect_to(root_url) unless @category.user == current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]
  def create
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    if @comment.save
      flash[:success] = 'コメントを投稿しました'
      redirect_to topic_path(@topic)
    else
      @comments = @topic.comments.page(params[:page]).per(100).includes([:user])
      @category = Category.new
      @categories = @topic.categories
      render template: 'topics/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @topic = @comment.topic
    if @comment.destroy
      flash[:success] = 'コメントを削除しました'
    end
    redirect_to topic_path(@topic)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :topic_id)
  end

  def correct_user
    @comment = Comment.find(params[:id])
    redirect_to(root_url) unless @comment.user == current_user
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  def index
    @topics = Topic.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def search
    @q = params[:search]
    if @q.empty?
      @topics = Topic.all.order(created_at: :desc).page(params[:page]).per(10)
    else
      @topics = Topic.order(created_at: :desc).where("title LIKE ?", "%#{@q}%")
      @comments = Comment.where("content LIKE ?", "%#{@q}%").includes([:topic])
      @categories = Category.where("name LIKE ?", "%#{@q}%").includes(topic: :categories)
    end
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.build(topic_params)
    if @topic.save
      flash[:success] = 'スレッドを作成しました！'
      redirect_to @topic
    else
      render 'new'
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @comment = Comment.new
    @comments = @topic.comments.page(params[:page]).per(100).includes([:user])
    @category = Category.new
    @categories = @topic.categories
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      flash[:success] = 'スレッドを編集しました！'
      redirect_to @topic
    else
      render 'edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      flash[:success] = 'スレッドを削除しました！'
    end
    redirect_to root_path
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end

  def correct_user
    @topic = Topic.find(params[:id])
    redirect_to(root_url) unless @topic.user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = '掲示板!!'
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/categories/_category.html.erb
<p>
  <%= category.name %>
  <% if current_user && category.user_id == current_user.id %>
    <%= link_to '削除', category_path(category), method: :delete %>
  <% end %>
</p>

app/views/categories/_category_form.html.erb
<% if current_user && @topic.user_id == current_user.id %>
  <%= form_for(@category, url: {controller: 'categories', action: 'create' }) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <%= f.hidden_field :topic_id, :value => topic.id %>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "＊30文字以内" %> 
    <%= f.submit "カテゴリを追加する" %>
  <% end %>
<% end %>

app/views/comments/_comment.html.erb
<div class="comment_box">
  <div>
    <font color=blue><%= comment.user.name %></font>
    <%= comment.created_at.strftime('%Y/%m/%d %H:%M')%>
  </div>
  <p><%= comment.content %></p>
  <% if current_user && comment.user_id == current_user.id %>
    <%= link_to '削除する', comment_path(comment), method: :delete %>
  <% end %>
</div>

app/views/comments/_comment_form.html.erb
<% if user_signed_in? %>
  <%= form_for(@comment, url: {controller: 'comments', action: 'create' }) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <%= f.hidden_field :topic_id, :value => topic.id %>
    <%= f.label :content %>
    <%= f.text_area :content, placeholder: "＊100文字以内", class: "form-control" %> 
    <div>
      <%= f.submit "投稿する", class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice.present? %>
  <p class="alert alert-success"><%= notice %></p>
<% elsif alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% else %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<!-- COPY RIGHT -->
<div class="footer">
  <div>
    <p>&copy; <%= Time.current.year %> 掲示板!! All Rights reserved.</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- header -->
<header>
  <nav class="navbar navbar-default">
    <div class="header-menu">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand"><%= link_to '掲示板!!', root_path %></div>
      </div>
      <div class="collapse navbar-collapse" id="navigation">
        <ul>  
          <% if user_signed_in? %>
            <li class="navbar-text navbar-right"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <li class="navbar-text navbar-right"><%= link_to '登録情報の変更', edit_user_registration_path(current_user) %></li>
            <li class="navbar-text navbar-right"><%= link_to 'スレッドの作成', new_topic_path %></li>
          <% else %>
            <li class="navbar-text navbar-right"><%= link_to '新規登録', new_user_registration_path %></li>
            <li class="navbar-text navbar-right"><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>
          <li class="navbar-text navbar-right"><%= link_to 'スレッド一覧', topics_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_javascript_include_tag.html.erb
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_meta_tags.html.erb
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<%= csp_meta_tag %>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_stylesheet_link_tag.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/meta_tags'%>
    <%= render 'layouts/stylesheet_link_tag'%>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>  
    <%= render 'layouts/footer' %>
    <%= render 'layouts/javascript_include_tag' %>
  </body>
</html>

app/views/topics/_categories_search_result.html.erb
<% categories.each do |category| %>
  <div class="topic_box">
    <%= link_to topic_path(category.topic) do %>
      <div class="topic_title_link"><%= category.topic.title%></div>
    <% end %>
　  <div class='categories'><%= render category.topic.categories %></div>
    <ul class="topic_info">
      <li><%= category.topic.created_at.strftime('%Y/%m/%d %H:%M') %></li>
      <li>コメント数<%= Comment.where(topic_id: category.topic.id).count %></li>
    </ul>
  </div>
<% end %>

app/views/topics/_comments_search_result.html.erb
<% comments.each do |comment| %>
  <div class="topic_box">
    <%= link_to topic_path(comment.topic) do %>
      <div class="topic_title_link"><%= comment.topic.title%></div>
    <% end %>
    <div><%= comment.content %></div>
    <ul class="topic_info">
      <li><%= comment.topic.created_at.strftime('%Y/%m/%d %H:%M') %></li>
      <li>コメント数<%= Comment.where(topic_id: comment.topic.id).count %></li>
    </ul>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="topic_box">
  <%= link_to topic_path(topic) do %>
    <div class="topic_title_link"><%= topic.title%></div>
    <ul class="topic_info">
      <li><%= topic.created_at.strftime('%Y/%m/%d %H:%M') %></li>
      <li>コメント数<%= Comment.where(topic_id: topic.id).count %></li>
    </ul>
  <% end %>
</div>

app/views/topics/_topics_search.html.erb
<div class="topic_search_form">
  <%= form_tag(search_topics_path, :method => 'get' ) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索'%>
  <% end %>
</div>

app/views/topics/edit.html.erb
<% provide(:title, 'スレッドの編集') %>
<h2>スレッドの作成</h2>
<%= form_for(@topic, url: { controller: 'topics', action: 'update' }) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="field">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, placeholder: "ex)プログラミング始めた件について", class: "form-control", autofocus: true %>
  </div>
  <div>
    <%= f.submit "修正する", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/topics/index.html.erb
<% provide(:title, 'スレッド一覧') %>
<%= render 'topics/topics_search' %>
<h3>スレッド一覧</h3>
<div>
  <%= render @topics %>
</div>
<div class="text-center"><%= paginate @topics %></div>

app/views/topics/new.html.erb
<% provide(:title, 'スレッドの作成') %>
<h2>スレッドの作成</h2>
<%= form_for(@topic, url: {controller: 'topics', action: 'create' }) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="field">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, placeholder: "ex)プログラミング始めた件について", class: "form-control", autofocus: true %>
  </div>
  <div>
    <%= f.submit "作成する", class: 'btn btn-primary form-control' %>
  </div>
<% end %>

app/views/topics/search.html.erb
<% provide(:title, '検索結果') %>
<%= render 'topics/topics_search' %>
<h3>検索結果</h3>
<% if @topics.empty? && @comments.empty? && @categories.empty? %>
  <p>検索はヒットしませんでした</p>
<% elsif @q.empty? %>
  <div><%= render @topics %></div>
  <div class="text-center"><%= paginate @topics %></div>
<% else %>
  <div>
    <%= render @topics %>
    <%= render "topics/comments_search_result", comments: @comments %>
    <%= render "topics/categories_search_result", categories: @categories %>
  </div>
<% end %>

app/views/topics/show.html.erb
<% provide(:title, "#{@topic.title}") %>
<%= render 'topics/topics_search' %>
<div class='topic-title'>
  <h3><%= @topic.title %></h3>
  <% if current_user && @topic.user_id == current_user.id %>
    <div>
      <%= link_to 'スレッドを編集する', edit_topic_path(@topic),class: 'btn btn-default' %>
      <%= link_to 'スレッドを削除する', "/topics/#{@topic.id}", method: :delete,class: 'btn btn-default' %>
    </div>
  <% end %>
</div>
<%= render 'categories/category_form', topic: @topic %>
<div class='categories'><%= render @categories %></div>
<%= render 'comments/comment_form', topic: @topic %>
<%= render @comments %>
<div class="text-center"><%= paginate @comments %></div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログインはこちら", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録はこちら", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた方はこちら", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>